GET localhost:9999/api/authorityGroups
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NTkwNjcyMDIsInVzZXJfbmFtZSI6ImFkbWluIiwiYXV0aG9yaXRpZXMiOlsiT0FVVEhfQURNSU4iLCJPQVVUSF9BRE1JTjIiXSwianRpIjoiNDcyZGY2YzYtMTdjMS00ZWRlLWEwMDYtYTQ0NzY1OTY5ZjI5IiwiY2xpZW50X2lkIjoidWkiLCJzY29wZSI6WyJ1aSJdfQ.Lb8kL_ZIeRc0JDlC-iRD6jH8hrsGaJZsS9XSSgHcKQNUVmYxe_cCruSuDvDv8wa_FxHFdJB75twi_qEiEr4QvJCmfouaW_Jx65sAAPBlGX9tIuXxTXPoZipvkvjjsumIUBc1vDqHYSbL4wOhEKrWgQs9Wcqb-Av8loF_ZMHxpu2ZQ05zfFqyhwx4jTgWNUaRyqC3-TsMcUgb0EZeq4Y2B-OnjOT9nMcXgKrQqYiN-svZXieWRY4VdXShT-ewJ29CZuviOKXoKl040GwYmhcptJY3T0ksLYJCHc7X2Ne_LkFi_s0SKzekAG_QztEAaU9iJ1wWgOOfNffw4lnEPRmeLw

###

POST localhost:9999/api/authorityGroups
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NTkwNjcyMDIsInVzZXJfbmFtZSI6ImFkbWluIiwiYXV0aG9yaXRpZXMiOlsiT0FVVEhfQURNSU4iLCJPQVVUSF9BRE1JTjIiXSwianRpIjoiNDcyZGY2YzYtMTdjMS00ZWRlLWEwMDYtYTQ0NzY1OTY5ZjI5IiwiY2xpZW50X2lkIjoidWkiLCJzY29wZSI6WyJ1aSJdfQ.Lb8kL_ZIeRc0JDlC-iRD6jH8hrsGaJZsS9XSSgHcKQNUVmYxe_cCruSuDvDv8wa_FxHFdJB75twi_qEiEr4QvJCmfouaW_Jx65sAAPBlGX9tIuXxTXPoZipvkvjjsumIUBc1vDqHYSbL4wOhEKrWgQs9Wcqb-Av8loF_ZMHxpu2ZQ05zfFqyhwx4jTgWNUaRyqC3-TsMcUgb0EZeq4Y2B-OnjOT9nMcXgKrQqYiN-svZXieWRY4VdXShT-ewJ29CZuviOKXoKl040GwYmhcptJY3T0ksLYJCHc7X2Ne_LkFi_s0SKzekAG_QztEAaU9iJ1wWgOOfNffw4lnEPRmeLw
Content-Type: application/json

{
  "id": 2,
  "name": "my Test group name3",
  "authorities": [
    {
      "id": 2
    }
  ]
}

###

GET localhost:9999/api/users/byAuthority/MCHAT_ADMIN
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNDk4NWRhNTMtNTZmOC00ZTI1LWEwMzAtMmZkZThiM2U0OWY3IiwidXNlcl9uYW1lIjoiYWRtaW4iLCJzY29wZSI6WyJ1aSJdLCJleHAiOjE1NjE0OTU5MzIsImF1dGhvcml0aWVzIjpbIk1DSEFUX0FETUlOIiwiT0FVVEhfQURNSU4iXSwianRpIjoiOWZiYWMxNmItMmJlZi00YmMwLWE3NjYtMzI4MjFiNDczNTk1IiwiY2xpZW50X2lkIjoidWkifQ.UEcwh_G0YwpuF6ftJ-VbIYm8s4EtlGnnzTIO4i0PnOHyDk3_Uje3U7dx-TvV6elExeaYZF_6Lrh9xTE_Gyk70X2SkgUxCOCeY-F3Gj4shZ45iS8ksQL_9lOFdeYSCRASTpJANE3ibLpW_7VyP2nJWJn9sXKWjmGdVzeb9mqwK71oblSQyjOhZZzwtxOXWChxumcojS8DN01JFPCWrnzYzK2_8BTNaHeA8_UT-QO_n-NvcgkXJRGwrqy0gkiO6HqmklJ9sAYNGfXO14GpYMSk19lWb4F0nQu3ebVDGcBuH_OSfnPNRCLgYjdrBBG4K0pzLJ-xa9mw2zn0awRgJoKELg

###