POST http://ui:ui_secret@localhost:9999/auth/oauth/token?username=admin&password=password&grant_type=password

###

POST http://ui:ui_secret@localhost:9999/oauth/token?username=admin&password=password&grant_type=password
Origin: ya.ru
###

POST http://ui:ui_secret@localhost:9999/oauth/token?username=doctor1&password=password&grant_type=password

###

POST http://ui:ui_secret@localhost:9999/oauth/token?username=patient1&password=password&grant_type=password

###

POST http://ui:ui_secret@localhost:9999/oauth/token?grant_type=refresh_token&refresh_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMTYyZjNiYzYtOThiYy0xMWU5LWEyYTMtMmEyYWUyZGJjY2U0IiwidXNlcl9uYW1lIjoiZG9jdG9yMSIsInNjb3BlIjpbInVpIl0sImF0aSI6IjVjYTE2ODRiLTViM2EtNGJhNi1iYWEyLTIzNTllNDA2YTMyMCIsImV4cCI6MTU2NDIyMjAzNywiYXV0aG9yaXRpZXMiOlsiRE9DVE9SIl0sImp0aSI6ImM0NDRiNzM0LTlhYTItNGM2Ny05ZTBlLWVjMjQ5NjBmN2MxNyIsImNsaWVudF9pZCI6InVpIn0.fm-byJwj3OTPt7r0rIXZ2NjMjH521yRNpbTsh4ZfTopnRL3rWf6ePc6_d4gW5s23AMbcU2Gh-fwLLg35OMk3VOXEP41wZB-p42vdM36eL1N3pvTcUUkZg3_1JaL3ZUWFfVhY7CqqOC7oJ1rMZogzo_sh5HPn2H-vUaYrAO1g3IFbeCbEpUVT6EHbTirtGHi03kyeAJavcCy_ePHkj_0nM2K81DNCiOJbGwubbC7UuD7wkKW1ZPIRMKgYqv6_76cAnD-UHofM8ABwH9tZvP3diBtIyuur6QpSNI9zSMWMcyXEH0tUjuLn0CrkKwEal06YDXJg9NVdPBECqX3gSO83sw

###
{
  "access_token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMTYyZjNiYzYtOThiYy0xMWU5LWEyYTMtMmEyYWUyZGJjY2U0IiwidXNlcl9uYW1lIjoiZG9jdG9yMSIsInNjb3BlIjpbInVpIl0sImV4cCI6MTU2MTY3MzIzNywiYXV0aG9yaXRpZXMiOlsiRE9DVE9SIl0sImp0aSI6IjVjYTE2ODRiLTViM2EtNGJhNi1iYWEyLTIzNTllNDA2YTMyMCIsImNsaWVudF9pZCI6InVpIn0.iDDB79A7tuU9CqORrsrupSfvFrCzLZ2wz7m3d7V40X_YtoTk0V_gHSv4BIOjH5ZbjMhzkazYaj7xtFdwmS9n7keoW6kHVAm_CgTwyVd08fWfGd31pRPqiDGf5edsT6t4W4kTK8-WYUy5h5ST3zYVTz11WMoeiBmHLp2LSFFJvC1Upn_d6ap6lWRxLaA62CE6ZktItlpU0TdOGf9_GLML7owv60uyhz8Sn8bm75h3zzrLXjA2prPdoruMQgpXwBocca_Iq_GmymfwfdXiu3nTwRPOoPnnZFeaBC3kg1Dol2c7uoroM0XR-yB8kOtD1omX_pmDmqr3Hl7VhHCPmb2cJA",
  "token_type": "bearer",
  "refresh_token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMTYyZjNiYzYtOThiYy0xMWU5LWEyYTMtMmEyYWUyZGJjY2U0IiwidXNlcl9uYW1lIjoiZG9jdG9yMSIsInNjb3BlIjpbInVpIl0sImF0aSI6IjVjYTE2ODRiLTViM2EtNGJhNi1iYWEyLTIzNTllNDA2YTMyMCIsImV4cCI6MTU2NDIyMjAzNywiYXV0aG9yaXRpZXMiOlsiRE9DVE9SIl0sImp0aSI6ImM0NDRiNzM0LTlhYTItNGM2Ny05ZTBlLWVjMjQ5NjBmN2MxNyIsImNsaWVudF9pZCI6InVpIn0.fm-byJwj3OTPt7r0rIXZ2NjMjH521yRNpbTsh4ZfTopnRL3rWf6ePc6_d4gW5s23AMbcU2Gh-fwLLg35OMk3VOXEP41wZB-p42vdM36eL1N3pvTcUUkZg3_1JaL3ZUWFfVhY7CqqOC7oJ1rMZogzo_sh5HPn2H-vUaYrAO1g3IFbeCbEpUVT6EHbTirtGHi03kyeAJavcCy_ePHkj_0nM2K81DNCiOJbGwubbC7UuD7wkKW1ZPIRMKgYqv6_76cAnD-UHofM8ABwH9tZvP3diBtIyuur6QpSNI9zSMWMcyXEH0tUjuLn0CrkKwEal06YDXJg9NVdPBECqX3gSO83sw",
  "expires_in": 43199,
  "scope": "ui",
  "user_id": "162f3bc6-98bc-11e9-a2a3-2a2ae2dbcce4",
  "jti": "5ca1684b-5b3a-4ba6-baa2-2359e406a320"
}
